#!/usr/bin/env bash
# Injects the Alipay native SDK + bridge plugin into the freshly generated
# Capacitor native projects (Android / iOS) at build time.
# The native projects are regenerated by `npx cap add` / `npx cap sync`,
# so custom native code must be (re)applied here rather than committed.
set -euo pipefail
cd "$(dirname "$0")/.."

# ---------------- Android ----------------
if [ -d native/android ]; then
  PKG=native/android/app/src/main/java/com/antmotors/app
  mkdir -p "$PKG"
  cat > "$PKG/AlipayPlugin.java" <<'JAVA'
package com.antmotors.app;

import android.app.Activity;
import android.os.Handler;
import android.os.Looper;

import com.alipay.sdk.app.PayTask;
import com.getcapacitor.JSObject;
import com.getcapacitor.Plugin;
import com.getcapacitor.PluginCall;
import com.getcapacitor.PluginMethod;
import com.getcapacitor.annotation.CapacitorPlugin;

import java.util.HashMap;
import java.util.Map;

@CapacitorPlugin(name = "Alipay")
public class AlipayPlugin extends Plugin {

    @PluginMethod
    public void pay(PluginCall call) {
        final String orderStr = call.getString("orderStr");
        if (orderStr == null || orderStr.isEmpty()) {
            call.reject("orderStr required");
            return;
        }
        final Activity activity = getActivity();
        if (activity == null) {
            call.reject("activity unavailable");
            return;
        }
        new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    PayTask payTask = new PayTask(activity);
                    final String result = payTask.payV2(orderStr, true);
                    final Map<String, String> map = parseAlipayResult(result);
                    new Handler(Looper.getMainLooper()).post(new Runnable() {
                        @Override
                        public void run() {
                            JSObject ret = new JSObject();
                            ret.put("resultStatus", map.get("resultStatus"));
                            ret.put("result", map.get("result"));
                            ret.put("memo", map.get("memo"));
                            call.resolve(ret);
                        }
                    });
                } catch (final Exception e) {
                    new Handler(Looper.getMainLooper()).post(new Runnable() {
                        @Override
                        public void run() {
                            call.reject("alipay_sdk_error: " + e.getMessage());
                        }
                    });
                }
            }
        }).start();
    }

    private static Map<String, String> parseAlipayResult(String raw) {
        Map<String, String> map = new HashMap<>();
        if (raw == null) return map;
        for (String pair : raw.split("&")) {
            int idx = pair.indexOf('=');
            if (idx > 0) {
                map.put(pair.substring(0, idx), pair.substring(idx + 1));
            }
        }
        return map;
    }
}
JAVA

  MF=native/android/app/src/main/java/com/antmotors/app/MainActivity.java
  if [ -f "$MF" ]; then
    python3 - "$MF" <<'PY'
import sys, io
p = sys.argv[1]
s = io.open(p, 'r', encoding='utf-8').read()
old = """package com.antmotors.app;

import com.getcapacitor.BridgeActivity;

public class MainActivity extends BridgeActivity {}"""
new = """package com.antmotors.app;

import com.getcapacitor.BridgeActivity;

public class MainActivity extends BridgeActivity {
    @Override
    public void onCreate(android.os.Bundle savedInstanceState) {
        registerPlugin(AlipayPlugin.class);
        super.onCreate(savedInstanceState);
    }
}"""
if old in s:
    io.open(p, 'w', encoding='utf-8').write(s.replace(old, new, 1))
PY
  fi

  BG=native/android/app/build.gradle
  if [ -f "$BG" ]; then
    python3 - "$BG" <<'PY'
import sys, io
p = sys.argv[1]
s = io.open(p, 'r', encoding='utf-8').read()
if "alipaysdk-android" not in s:
    s = s.replace(
        "    implementation project(':capacitor-cordova-android-plugins')\n}",
        "    implementation project(':capacitor-cordova-android-plugins')\n    implementation 'com.alipay.sdk:alipaysdk-android:15.8.11'\n}")
    s = s.replace(
        """repositories {
    flatDir{
        dirs '../capacitor-cordova-android-plugins/src/main/libs', 'libs'
    }
}""",
        """repositories {
    flatDir{
        dirs '../capacitor-cordova-android-plugins/src/main/libs', 'libs'
    }
    maven { url 'https://maven.alipay.com/repository/public' }
}""")
    io.open(p, 'w', encoding='utf-8').write(s)
PY
  fi
  echo "[alipay] Android native injected"
fi

# ---------------- iOS ----------------
if [ -d native/ios/App ]; then
  cat > native/ios/App/App/AlipayPlugin.swift <<'SWIFT'
import Foundation
import Capacitor
import AlipaySDK

@objc(AlipayPlugin)
public class AlipayPlugin: CAPPlugin {
    @objc func pay(_ call: CAPPluginCall) {
        guard let orderStr = call.getString("orderStr") else {
            call.reject("orderStr required")
            return
        }
        DispatchQueue.main.async {
            AlipaySDK.defaultService()?.payOrder(orderStr, fromScheme: "antoto") { result in
                var dict: [String: Any] = [:]
                if let r = result as? [String: Any] {
                    dict = r
                }
                call.resolve(dict)
            }
        }
    }
}
SWIFT

  cat > native/ios/App/Podfile <<'POD'
platform :ios, '15.0'
target 'App' do
  use_frameworks! :linkage => :static
  pod 'AlipaySDK-iOS'
end
POD

  SC=native/ios/App/App/SceneDelegate.swift
  if [ -f "$SC" ]; then
    python3 - "$SC" <<'PY'
import sys, io
p = sys.argv[1]
s = io.open(p, 'r', encoding='utf-8').read()
old = """import UIKit
import Capacitor

class SceneDelegate: UIResponder, UIWindowSceneDelegate {
    var window: UIWindow?

    func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
        guard let windowScene = scene as? UIWindowScene else { return }

        window = UIWindow(windowScene: windowScene)
        window?.rootViewController = CAPBridgeViewController()
        window?.makeKeyAndVisible()

        SceneDelegateProxy.shared.scene(scene, willConnectTo: session, options: connectionOptions)
    }

    func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
        SceneDelegateProxy.shared.scene(scene, openURLContexts: URLContexts)
    }

    func scene(_ scene: UIScene, continue userActivity: NSUserActivity) {
        SceneDelegateProxy.shared.scene(scene, continue: userActivity)
    }
}"""
new = """import UIKit
import Capacitor
import AlipaySDK

class SceneDelegate: UIResponder, UIWindowSceneDelegate {
    var window: UIWindow?
    private var alipayRegistered = false

    func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
        guard let windowScene = scene as? UIWindowScene else { return }

        window = UIWindow(windowScene: windowScene)
        window?.rootViewController = CAPBridgeViewController()
        window?.makeKeyAndVisible()

        SceneDelegateProxy.shared.scene(scene, willConnectTo: session, options: connectionOptions)
    }

    func sceneDidBecomeActive(_ scene: UIScene) {
        if !alipayRegistered {
            if let vc = window?.rootViewController as? CAPBridgeViewController, let bridge = vc.bridge {
                bridge.registerPluginInstance(AlipayPlugin())
                alipayRegistered = true
            }
        }
    }

    func scene(_ scene: UIScene, openURLContexts URLContexts: Set<UIOpenURLContext>) {
        if let url = URLContexts.first?.url {
            AlipaySDK.defaultService()?.processOrder(withPaymentResult: url)
        }
        SceneDelegateProxy.shared.scene(scene, openURLContexts: URLContexts)
    }

    func scene(_ scene: UIScene, continue userActivity: NSUserActivity) {
        SceneDelegateProxy.shared.scene(scene, continue: userActivity)
    }
}"""
if old in s:
    io.open(p, 'w', encoding='utf-8').write(s.replace(old, new, 1))
PY
  fi

  # Add AlipayPlugin.swift to the Xcode project (file ref + compile source)
  PX=native/ios/App/App.xcodeproj/project.pbxproj
  if [ -f "$PX" ]; then
    python3 - "$PX" <<'PY'
import sys, io, secrets
p = sys.argv[1]
s = io.open(p, 'r', encoding='utf-8').read()
if "AlipayPlugin.swift in Sources" in s:
    print("[alipay] iOS pbxproj already patched")
    raise SystemExit(0)
if "SceneDelegate.swift in Sources" not in s:
    print("[alipay] SceneDelegate anchor missing, skip pbxproj patch")
    raise SystemExit(0)
def uuid():
    return secrets.token_hex(12).upper()  # 24 hex chars like Xcode style
ref = uuid()
bld = uuid()
# PBXBuildFile entry
s = s.replace(
    "		9582B6832FE993A70072D4E8 /* SceneDelegate.swift in Sources */ = {isa = PBXBuildFile; fileRef = 9582B6822FE993A50072D4E8 /* SceneDelegate.swift */; };",
    "		9582B6832FE993A70072D4E8 /* SceneDelegate.swift in Sources */ = {isa = PBXBuildFile; fileRef = 9582B6822FE993A50072D4E8 /* SceneDelegate.swift */; };\n\t\t%s /* AlipayPlugin.swift in Sources */ = {isa = PBXBuildFile; fileRef = %s /* AlipayPlugin.swift */; };" % (bld, ref))
# PBXFileReference entry
s = s.replace(
    "		9582B6822FE993A50072D4E8 /* SceneDelegate.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = SceneDelegate.swift; sourceTree = \"<group>\"; };",
    "		9582B6822FE993A50072D4E8 /* SceneDelegate.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = SceneDelegate.swift; sourceTree = \"<group>\"; };\n\t\t%s /* AlipayPlugin.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = AlipayPlugin.swift; sourceTree = \"<group>\"; };" % ref)
# group list (under SceneDelegate.swift)
s = s.replace(
    "				9582B6822FE993A50072D4E8 /* SceneDelegate.swift */,",
    "				9582B6822FE993A50072D4E8 /* SceneDelegate.swift */,\n\t\t\t\t\t%s /* AlipayPlugin.swift */," % ref)
# sources build phase
s = s.replace(
    "				9582B6832FE993A70072D4E8 /* SceneDelegate.swift in Sources */,",
    "				9582B6832FE993A70072D4E8 /* SceneDelegate.swift in Sources */,\n\t\t\t\t%s /* AlipayPlugin.swift in Sources */," % bld)
io.open(p, 'w', encoding='utf-8').write(s)
print("[alipay] iOS pbxproj patched (ref=%s build=%s)" % (ref, bld))
PY
  fi
  echo "[alipay] iOS native injected"
fi

echo "Alipay native integration done"
